// <auto-generated>
// Rewired Constants
// This list was generated on 2022/07/29 0:15:32
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "横移動")]
        public const int MoveHorizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "上下移動")]
        public const int MoveVertical = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ジャンプ しゃがみ・カメラ下移動")]
        public const int SiteVertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "左右カメラ移動")]
        public const int SiteHorizontal = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "回避・ダッシュ")]
        public const int Avoid = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "アクションボタン")]
        public const int Interact = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "アイテム切り替え")]
        public const int ItemChoice = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "魔法切り替え")]
        public const int MagicChoice = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "アイテム使用")]
        public const int ItemUse = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "弱攻撃")]
        public const int Fire1 = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "強攻撃")]
        public const int Fire2 = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ガード")]
        public const int Guard = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "特殊行動")]
        public const int Arts = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "武器持ち手変更")]
        public const int WeponHandChange = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "メニュー")]
        public const int Menu = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "連携ボタン")]
        public const int Combination = 22;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVertical")]
        public const int UIVertical = 33;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 34;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int Cancel = 41;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Submit")]
        public const int Submit = 42;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "TipsOn")]
        public const int TipsOn = 44;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int UI = 1;
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
    }
}
