// <auto-generated>
// Rewired Constants
// This list was generated on 2022/02/02 2:22:50
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal")]
        public const int _axisHorizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical")]
        public const int _axisVertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "SiteHorizontal")]
        public const int SiteHorizontal = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "SiteVertical")]
        public const int SiteVertical = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Avoid")]
        public const int Avoid = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int Interact = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ItemChoice")]
        public const int ItemChoice = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MagicChoice")]
        public const int MagicChoice = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ItemUse")]
        public const int ItemUse = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "sAttack")]
        public const int sAttack = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "bAttack")]
        public const int bAttack = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Guard")]
        public const int Guard = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Arts")]
        public const int Arts = 26;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "WeaponChange")]
        public const int WeaponChange = 27;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int Combination = 29;
        // System
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "System", friendlyName = "SystemPause")]
        public const int SystemPause = 13;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Move Horizontal")]
        public const int UIHorizontal = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Move Vertical")]
        public const int UIVertical = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Submit")]
        public const int UISubmit = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Cancel")]
        public const int UICancel = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "Action0")]
        public const int TipsOn = 30;
        // Inventory
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Toggle Inventory")]
        public const int InventoryToggle = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Move")]
        public const int InventoryMove = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Equip")]
        public const int InventoryEquip = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Use")]
        public const int InventoryUse = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Equip or Use")]
        public const int InventoryEquipOrUse = 22;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Drop")]
        public const int InventoryDrop = 23;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Next")]
        public const int InventoryNext = 24;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Inventory", friendlyName = "Previous")]
        public const int InventoryPrev = 25;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int System = 1;
        public const int UI = 2;
        public const int Inventory = 3;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
            public const int Player1 = 1;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 0;
    }
    public static partial class CustomController {
        public static partial class TouchController {
            public const int sourceId = 0;
            public const string name = "TouchController";
            public static readonly System.Guid typeGuid = new System.Guid("00000000-0000-0000-0000-000000000000");
            public static partial class Axis {
                public const int Horizontal = 0;
                public const int Vertical = 1;
            }
            public static partial class Button {
                public const int Jump = 2;
                public const int Jetpack = 3;
                public const int Run = 4;
                public const int Dash = 5;
                public const int Shoot = 6;
                public const int Reload = 7;
                public const int SwitchWeapon = 8;
                public const int Pause = 9;
            }
        }
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
